"use client";
import { useState } from "react";

export function ProjectDemo({slug}:{slug:string}){
 if(slug==="water-digital-twin") return <WaterDemo/>;
 if(slug==="chip-devops") return <ChipDemo/>;
 if(slug==="danceholic") return <DanceDemo/>;
 if(slug==="opengov-ai-os") return <Configurator/>;
 return <CareDemo/>;
}
function DemoLabel(){return <div className="demo-label"><span/>INTERACTIVE DEMO · 模拟数据</div>}
function CareDemo(){const [view,setView]=useState("老人端");return <div className="demo-panel care-demo"><DemoLabel/><div className="demo-tabs">{["老人端","家属端","社区端"].map(v=><button key={v} onClick={()=>setView(v)} className={view===v?"active":""}>{v}</button>)}</div><div className="care-surface"><div><small>{view} / 今日</small><h3>{view==="老人端"?"早上好，今天先量血压吧":view==="家属端"?"家人今日状态平稳":"今日随访队列"}</h3><p>{view==="老人端"?"记录后，我会把趋势讲得简单一些。":view==="家属端"?"已完成 2 项记录，无高风险提醒。":"3 位用户需要温和提醒，1 项待人工确认。"}</p></div><div className="vital-grid"><span><i>血压</i><b>128/78</b><small>演示 mmHg</small></span><span><i>心率</i><b>72</b><small>演示 bpm</small></span><span><i>趋势</i><b>平稳</b><small>近 7 日</small></span></div></div><p className="safety-note">医疗安全边界：不代替医生、不诊断、不调整剂量；高风险情况提示联系医生或急救机构。</p></div>}
function WaterDemo(){const [scene,setScene]=useState("正常");const copy={正常:"库区水位处于演示正常范围，监测节点运行平稳。",预警:"上游降雨与入库流量上升，建议核查 2 个风险节点。",应急:"演示应急态：启动人工复核，联动预案与影响范围分析。"}[scene];return <div className={`demo-panel water-demo scene-${scene}`}><DemoLabel/><div className="scene-switch">{["正常","预警","应急"].map(s=><button key={s} onClick={()=>setScene(s)} className={scene===s?"active":""}>{s}</button>)}</div><div className="twin-canvas"><div className="twin-grid"/><div className="terrain t1"/><div className="terrain t2"/><div className="reservoir"/><button className="map-point p1" aria-label="查看大坝监测点">01</button><button className="map-point p2" aria-label="查看上游监测点">02</button><div className="twin-readout"><small>AI ENGINEERING BRIEF</small><strong>{scene}场景 · 演示</strong><p>{copy}</p><span>水位 512.8m · 入库 142m³/s · 风险点 {scene==="正常"?0:2}</span></div></div></div>}
const chipSteps=["RTL 提交","静态检查","仿真回归","AI 日志分析","创建缺陷","板级测试","追溯更新"];
function ChipDemo(){const [active,setActive]=useState(0);return <div className="demo-panel chip-demo"><DemoLabel/><div className="chip-flow">{chipSteps.map((s,i)=><button key={s} onClick={()=>setActive(i)} className={active===i?"active":i<active?"done":""}><span>{String(i+1).padStart(2,"0")}</span><b>{s}</b><i/></button>)}</div><div className="chip-console"><div><small>CURRENT NODE</small><strong>{chipSteps[active]}</strong><p>{active<2?"输入：commit a81f · 责任人：RTL Engineer":active<5?"检测到模拟错误簇：reset sequence / 3 cases。AI 提供候选根因，等待工程师确认。":"板级测试结果已回传，需求—提交—测试链路更新。"}</p></div><button onClick={()=>setActive((active+1)%chipSteps.length)}>运行下一节点 →</button></div></div>}
function Skeleton({variant}:{variant:"coach"|"student"}){return <div className={`pose ${variant}`}><i className="pose-head"/><i className="pose-body"/><i className="pose-arm a1"/><i className="pose-arm a2"/><i className="pose-leg l1"/><i className="pose-leg l2"/><span className="joint j1"/><span className="joint j2"/><span className="joint j3"/><span className="joint j4"/></div>}
function DanceDemo(){const [beat,setBeat]=useState(3);return <div className="demo-panel dance-demo"><DemoLabel/><div className="video-compare"><div><small>教练 / COACH</small><Skeleton variant="coach"/></div><div><small>学员 / LEARNER</small><Skeleton variant="student"/></div></div><div className="motion-timeline">{[1,2,3,4,5,6,7,8].map(n=><button key={n} onClick={()=>setBeat(n)} className={beat===n?"active":""}>{n}</button>)}</div><div className="body-analysis">{[["肩部","稳定"],["手臂","角度不足"],["核心","需加强"],["腿部","慢 0.2s"]].map(([a,b])=><span key={a}><i>{a}</i><b>{b}</b></span>)}</div><p className="ai-suggestion">第 {beat} 个八拍：{beat===3?"手臂展开角度不足，重心转换慢约 0.2 秒。":"动作轨迹接近参考，注意保持核心稳定。"}</p></div>}
function Configurator(){const industries=["政府","国企","水利设计院","芯片企业","咨询机构"];const [industry,setIndustry]=useState("水利设计院");const [step,setStep]=useState(2);return <div className="demo-panel config-demo"><DemoLabel/><div className="config-progress">{["部署主体","选择行业","AI 能力","插件","门户预览"].map((s,i)=><button className={i<=step?"active":""} onClick={()=>setStep(i)} key={s}><span>0{i+1}</span>{s}</button>)}</div><div className="config-body"><div><small>行业模板</small><div className="industry-options">{industries.map(i=><button key={i} className={industry===i?"active":""} onClick={()=>setIndustry(i)}>{i}</button>)}</div><pre>{`{\n  "industry": "${industry}",\n  "agents": ["知识助手", "报告助手"],\n  "deployment": "private"\n}`}</pre></div><div className="portal-preview"><header><i/> {industry} AI 门户</header><aside><span>工作台</span><span>知识库</span><span>Agent</span><span>审计日志</span></aside><main><div/><div/><div/><section/></main></div></div></div>}
